name: "Geolocation"

# This will run once a week and on pull requests
on:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  geolocalize:
    name: "Fix geolocation data"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.2' # The R version to download (if necessary) and use.
      - name: Requirements before R packages
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Make sure renv is there (or make it if not)
        run: Rscript -e 'source("scripts/datacleaning/renv.R")'
      - name: Run the file
        run: Rscript scripts/datacleaning/02_geolocation.R
        env:
          GEOLOCATION_API_KEY: ${{ secrets.GEOLOCATION_API_KEY }}
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: geolocation_csv_file
          path: data/geolocation/
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}