name: "Clean the GenBank metadata"

# This will run hourly, on PRs, and on pushes from all branches
on:
  push:
    branches:
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  make_csv:
    name: "Convert the raw data to CSV"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: "Read Excel file"
        run: julia --project scripts/datacleaning/01_excel_to_csv.jl
        env:
          PYTHON: ""