name: "Clean the GenBank metadata"

# This will run hourly, on PRs, and on pushes from all branches
on:
  push:
    branches:
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  find_hosts:
    name: "Find hosts in GBIF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia 1.4.0 
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - name: Build dependencies 
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Read Excel file
        run: julia --project scripts/datacleaning/01_excel_to_csv.jl
        env:
          PYTHON: ""
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: hostnames
          path: data/hostnames/