name: "Clean the GenBank metadata"

# This will run hourly, on PRs, and on pushes from all branches
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  geolocalize:
    name: "Fix geolocation data"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.2' # The R version to download (if necessary) and use.
      - name: Requirements before R packages
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Make sure renv is there (or make it if not)
        run: Rscript -e 'source("scripts/datacleaning/renv.R")'
      - name: Run the file
        run: Rscript scripts/datacleaning/02_geolocation.R
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: geolocation_csv_file
          path: data/geolocation/
  find_hosts:
    name: "Find hosts in GBIF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia 1.4.0 
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - name: Build dependencies 
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Get names from GBIF
        run: julia --project scripts/datacleaning/01_extract_hosts.jl
        env:
          PYTHON: ""
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: hostnames_csv_files
          path: data/hostnames/
  get_occurrences:
    name: Get occurrences for known hosts
    needs: find_hosts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve the CSV files with host taxonomy
        uses: actions/download-artifact@v1
        with:
          name: hostnames_csv_files
          path: data/hostnames/
      - name: Setup Julia 1.4.0 
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - name: Build dependencies 
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Get occurrences from GBIF
        run: julia --project scripts/occurrences/01_occurrences.jl
        env:
          PYTHON: ""
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: occurrences_csv_files
          path: data/occurrences/
  get_interactions:
      name: Get interactions for known hosts and cleaned viruses
      needs: find_hosts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Retrieve the CSV files with host taxonomy
          uses: actions/download-artifact@v1
          with:
            name: hostnames_csv_files
            path: data/hostnames/
        - name: Setup Julia 1.4.0 
          uses: julia-actions/setup-julia@latest
          with:
            version: 1.4.0
        - name: Build dependencies 
          uses: julia-actions/julia-buildpkg@latest
          env:
            PYTHON: ""
        - name: Aggregate interaction data
          run: julia --project scripts/network/01_generate_network_files.jl
          env:
            PYTHON: ""
        - name: Upload usable data folder
          uses: actions/upload-artifact@v1
          with:
            name: interactions_csv_file
            path: data/network/
